In [1]:
a = ["0", 1, "two", "3", 4]

In [2]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [3]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
print(np.__version__)

1.21.5


In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [8]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
type(b)
b.dtype

dtype('float64')

In [9]:
type(b)

numpy.ndarray

In [10]:
c = np.array([20, 1, 2, 3, 4])

In [11]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [12]:
c[4] = 0
c

array([100,   1,   2,   3,   0])

In [13]:
a = np.array([10, 2, 30, 40,50])
a[1] = 20

In [14]:
a

array([10, 20, 30, 40, 50])

In [15]:
d = c[1:4]
d

array([1, 2, 3])

In [16]:
c[3:5] = 300,400
c

array([100,   1,   2, 300, 400])

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [18]:
print(arr[:4])

[1 2 3 4]


In [19]:
print(arr[1:5:])

[2 3 4 5]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
print(arr[1::2])

[2 4 6 8]


In [23]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [24]:
d = c[select]
d

array([100,   2, 300, 400])

In [25]:
c[select] = 1000000

c

array([1000000,       1, 1000000, 1000000, 1000000])

In [26]:
a= np.array([0:5])
a

SyntaxError: invalid syntax (310410794.py, line 1)